"""phase 3 full schema

Revision ID: 22a3491cce1a
Revises: d2ed60dc3a9d
Create Date: 2026-05-06 17:12:29.479562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22a3491cce1a'
down_revision: Union[str, Sequence[str], None] = 'd2ed60dc3a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team_abbr', sa.String(), nullable=False),
    sa.Column('away_team_abbr', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nba_schedule_game_date'), 'nba_schedule', ['game_date'], unique=False)
    op.create_index(op.f('ix_nba_schedule_game_id'), 'nba_schedule', ['game_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yahoo_player_key', sa.String(), nullable=False),
    sa.Column('yahoo_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('eligible_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_position', sa.String(), nullable=True),
    sa.Column('nba_team_abbr', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_yahoo_player_id'), 'players', ['yahoo_player_id'], unique=False)
    op.create_index(op.f('ix_players_yahoo_player_key'), 'players', ['yahoo_player_key'], unique=True)
    op.create_table('nba_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_abbr', sa.String(), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('minutes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game')
    )
    op.create_index(op.f('ix_nba_game_logs_game_date'), 'nba_game_logs', ['game_date'], unique=False)
    op.create_index(op.f('ix_nba_game_logs_game_id'), 'nba_game_logs', ['game_id'], unique=False)
    op.create_index(op.f('ix_nba_game_logs_player_id'), 'nba_game_logs', ['player_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('nba_team_abbr', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_news_source')
    )
    op.create_index(op.f('ix_news_items_player_id'), 'news_items', ['player_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_key', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('stat_id', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'league_key', 'scope', 'stat_id', 'as_of_date', name='uq_player_stat_snap')
    )
    op.create_index(op.f('ix_player_stats_league_key'), 'player_stats', ['league_key'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_table('free_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('waiver_status', sa.String(), nullable=True),
    sa.Column('percent_owned', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', name='uq_league_fa')
    )
    op.create_index(op.f('ix_free_agents_league_id'), 'free_agents', ['league_id'], unique=False)
    op.create_index(op.f('ix_free_agents_player_id'), 'free_agents', ['player_id'], unique=False)
    op.create_table('projection_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('projected_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'league_id', 'horizon', name='uq_projection_cache_unique')
    )
    op.create_index(op.f('ix_projection_cache_league_id'), 'projection_cache', ['league_id'], unique=False)
    op.create_index(op.f('ix_projection_cache_player_id'), 'projection_cache', ['player_id'], unique=False)
    op.create_index(op.f('ix_projection_cache_stale'), 'projection_cache', ['stale'], unique=False)
    op.create_table('projection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('projected_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'league_id', 'horizon', 'snapshot_date', name='uq_projection_history_unique')
    )
    op.create_index(op.f('ix_projection_history_league_id'), 'projection_history', ['league_id'], unique=False)
    op.create_index(op.f('ix_projection_history_player_id'), 'projection_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_projection_history_snapshot_date'), 'projection_history', ['snapshot_date'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_key', sa.String(), nullable=False),
    sa.Column('team_id_in_league', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('is_user_team', sa.Boolean(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'team_key', name='uq_league_team')
    )
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_teams_team_key'), 'teams', ['team_key'], unique=False)
    op.create_table('roster_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('selected_position', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_team_player')
    )
    op.create_index(op.f('ix_roster_players_player_id'), 'roster_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_roster_players_team_id'), 'roster_players', ['team_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('trade_key', sa.String(), nullable=False),
    sa.Column('proposer_team_id', sa.Integer(), nullable=True),
    sa.Column('accepter_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('players_offered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('players_received', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepter_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposer_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'trade_key', name='uq_league_trade')
    )
    op.create_index(op.f('ix_trades_league_id'), 'trades', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_league_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_roster_players_team_id'), table_name='roster_players')
    op.drop_index(op.f('ix_roster_players_player_id'), table_name='roster_players')
    op.drop_table('roster_players')
    op.drop_index(op.f('ix_teams_team_key'), table_name='teams')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projection_history_snapshot_date'), table_name='projection_history')
    op.drop_index(op.f('ix_projection_history_player_id'), table_name='projection_history')
    op.drop_index(op.f('ix_projection_history_league_id'), table_name='projection_history')
    op.drop_table('projection_history')
    op.drop_index(op.f('ix_projection_cache_stale'), table_name='projection_cache')
    op.drop_index(op.f('ix_projection_cache_player_id'), table_name='projection_cache')
    op.drop_index(op.f('ix_projection_cache_league_id'), table_name='projection_cache')
    op.drop_table('projection_cache')
    op.drop_index(op.f('ix_free_agents_player_id'), table_name='free_agents')
    op.drop_index(op.f('ix_free_agents_league_id'), table_name='free_agents')
    op.drop_table('free_agents')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_league_key'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_news_items_player_id'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_nba_game_logs_player_id'), table_name='nba_game_logs')
    op.drop_index(op.f('ix_nba_game_logs_game_id'), table_name='nba_game_logs')
    op.drop_index(op.f('ix_nba_game_logs_game_date'), table_name='nba_game_logs')
    op.drop_table('nba_game_logs')
    op.drop_index(op.f('ix_players_yahoo_player_key'), table_name='players')
    op.drop_index(op.f('ix_players_yahoo_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_nba_schedule_game_id'), table_name='nba_schedule')
    op.drop_index(op.f('ix_nba_schedule_game_date'), table_name='nba_schedule')
    op.drop_table('nba_schedule')
    # ### end Alembic commands ###
