"""phase 3.5 enrich teams and players

Revision ID: 6b7eb218895a
Revises: 22a3491cce1a
Create Date: 2026-05-06 17:37:19.940014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7eb218895a'
down_revision: Union[str, Sequence[str], None] = '22a3491cce1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free_agents', 'percent_owned')
    op.add_column('players', sa.Column('uniform_number', sa.String(), nullable=True))
    op.add_column('players', sa.Column('percent_owned', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('percent_owned_delta', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('percent_started', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('draft_avg_pick', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('players', sa.Column('draft_avg_round', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('players', sa.Column('draft_avg_cost', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('players', sa.Column('draft_percent_drafted', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('teams', sa.Column('manager_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('points_for', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('teams', sa.Column('points_against', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('teams', sa.Column('clinched_playoffs', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('division_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('faab_balance', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('waiver_priority', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('number_of_moves', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('number_of_trades', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('draft_grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'draft_grade')
    op.drop_column('teams', 'number_of_trades')
    op.drop_column('teams', 'number_of_moves')
    op.drop_column('teams', 'waiver_priority')
    op.drop_column('teams', 'faab_balance')
    op.drop_column('teams', 'division_id')
    op.drop_column('teams', 'clinched_playoffs')
    op.drop_column('teams', 'points_against')
    op.drop_column('teams', 'points_for')
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'manager_id')
    op.drop_column('players', 'draft_percent_drafted')
    op.drop_column('players', 'draft_avg_cost')
    op.drop_column('players', 'draft_avg_round')
    op.drop_column('players', 'draft_avg_pick')
    op.drop_column('players', 'percent_started')
    op.drop_column('players', 'percent_owned_delta')
    op.drop_column('players', 'percent_owned')
    op.drop_column('players', 'uniform_number')
    op.add_column('free_agents', sa.Column('percent_owned', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
