"""phase 2 users and leagues

Revision ID: d2ed60dc3a9d
Revises: 029db6dc464b
Create Date: 2026-05-06 16:55:08.585517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ed60dc3a9d'
down_revision: Union[str, Sequence[str], None] = '029db6dc464b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yahoo_guid', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('auth_broken', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_yahoo_guid'), 'users', ['yahoo_guid'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scoring_type', sa.String(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_key', name='uq_user_league')
    )
    op.create_index(op.f('ix_leagues_league_key'), 'leagues', ['league_key'], unique=False)
    op.create_index(op.f('ix_leagues_user_id'), 'leagues', ['user_id'], unique=False)
    op.drop_table('_phase1_smoke')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_phase1_smoke',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_phase1_smoke_pkey'))
    )
    op.drop_index(op.f('ix_leagues_user_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_league_key'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_yahoo_guid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
